// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"go_jaeger_demo/order/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/order",
				Handler: orderHandler(serverCtx),
			},
		},
	)
}
